(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var n;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var p="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var q=ba(this);function r(a,b){if(b)a:{var c=q;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&p(c,a,{configurable:!0,writable:!0,value:b})}}
r("Symbol",function(a){function b(h){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(h||"")+"_"+e++,h)}function c(h,g){this.g=h;p(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
r("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=q[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&p(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ca(aa(this))}})}return a});function ca(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function t(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}var da="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ea;
if("function"==typeof Object.setPrototypeOf)ea=Object.setPrototypeOf;else{var fa;a:{var ha={a:!0},ia={};try{ia.__proto__=ha;fa=ia.a;break a}catch(a){}fa=!1}ea=fa?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ja=ea;function ma(){this.l=!1;this.h=null;this.i=void 0;this.g=1;this.A=0;this.j=null}function na(a){if(a.l)throw new TypeError("Generator is already running");a.l=!0}ma.prototype.s=function(a){this.i=a};
function oa(a,b){a.j={ba:b,ca:!0};a.g=a.A}ma.prototype.return=function(a){this.j={return:a};this.g=this.A};function u(a,b,c){a.g=c;return{value:b}}function pa(a){this.g=new ma;this.h=a}function qa(a,b){na(a.g);var c=a.g.h;if(c)return ra(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return v(a)}
function ra(a,b,c,d){try{var e=b.call(a.g.h,c);if(!(e instanceof Object))throw new TypeError("Iterator result "+e+" is not an object");if(!e.done)return a.g.l=!1,e;var h=e.value}catch(g){return a.g.h=null,oa(a.g,g),v(a)}a.g.h=null;d.call(a.g,h);return v(a)}function v(a){for(;a.g.g;)try{var b=a.h(a.g);if(b)return a.g.l=!1,{value:b.value,done:!1}}catch(c){a.g.i=void 0,oa(a.g,c)}a.g.l=!1;if(a.g.j){b=a.g.j;a.g.j=null;if(b.ca)throw b.ba;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function sa(a){this.next=function(b){na(a.g);a.g.h?b=ra(a,a.g.h.next,b,a.g.s):(a.g.s(b),b=v(a));return b};this.throw=function(b){na(a.g);a.g.h?b=ra(a,a.g.h["throw"],b,a.g.s):(oa(a.g,b),b=v(a));return b};this.return=function(b){return qa(a,b)};this[Symbol.iterator]=function(){return this}}function ta(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function h(g){g.done?d(g.value):Promise.resolve(g.value).then(b,c).then(h,e)}h(a.next())})}
function w(a){return ta(new sa(new pa(a)))}
r("Promise",function(a){function b(g){this.h=0;this.i=void 0;this.g=[];this.A=!1;var f=this.j();try{g(f.resolve,f.reject)}catch(k){f.reject(k)}}function c(){this.g=null}function d(g){return g instanceof b?g:new b(function(f){f(g)})}if(a)return a;c.prototype.h=function(g){if(null==this.g){this.g=[];var f=this;this.i(function(){f.l()})}this.g.push(g)};var e=q.setTimeout;c.prototype.i=function(g){e(g,0)};c.prototype.l=function(){for(;this.g&&this.g.length;){var g=this.g;this.g=[];for(var f=0;f<g.length;++f){var k=
g[f];g[f]=null;try{k()}catch(l){this.j(l)}}}this.g=null};c.prototype.j=function(g){this.i(function(){throw g;})};b.prototype.j=function(){function g(l){return function(m){k||(k=!0,l.call(f,m))}}var f=this,k=!1;return{resolve:g(this.X),reject:g(this.l)}};b.prototype.X=function(g){if(g===this)this.l(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.Z(g);else{a:switch(typeof g){case "object":var f=null!=g;break a;case "function":f=!0;break a;default:f=!1}f?this.W(g):this.s(g)}};
b.prototype.W=function(g){var f=void 0;try{f=g.then}catch(k){this.l(k);return}"function"==typeof f?this.aa(f,g):this.s(g)};b.prototype.l=function(g){this.V(2,g)};b.prototype.s=function(g){this.V(1,g)};b.prototype.V=function(g,f){if(0!=this.h)throw Error("Cannot settle("+g+", "+f+"): Promise already settled in state"+this.h);this.h=g;this.i=f;2===this.h&&this.Y();this.da()};b.prototype.Y=function(){var g=this;e(function(){if(g.ea()){var f=q.console;"undefined"!==typeof f&&f.error(g.i)}},1)};b.prototype.ea=
function(){if(this.A)return!1;var g=q.CustomEvent,f=q.Event,k=q.dispatchEvent;if("undefined"===typeof k)return!0;"function"===typeof g?g=new g("unhandledrejection",{cancelable:!0}):"function"===typeof f?g=new f("unhandledrejection",{cancelable:!0}):(g=q.document.createEvent("CustomEvent"),g.initCustomEvent("unhandledrejection",!1,!0,g));g.promise=this;g.reason=this.i;return k(g)};b.prototype.da=function(){if(null!=this.g){for(var g=0;g<this.g.length;++g)h.h(this.g[g]);this.g=null}};var h=new c;b.prototype.Z=
function(g){var f=this.j();g.B(f.resolve,f.reject)};b.prototype.aa=function(g,f){var k=this.j();try{g.call(f,k.resolve,k.reject)}catch(l){k.reject(l)}};b.prototype.then=function(g,f){function k(B,F){return"function"==typeof B?function(ka){try{l(B(ka))}catch(la){m(la)}}:F}var l,m,z=new b(function(B,F){l=B;m=F});this.B(k(g,l),k(f,m));return z};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.B=function(g,f){function k(){switch(l.h){case 1:g(l.i);break;case 2:f(l.i);break;default:throw Error("Unexpected state: "+
l.h);}}var l=this;null==this.g?h.h(k):this.g.push(k);this.A=!0};b.resolve=d;b.reject=function(g){return new b(function(f,k){k(g)})};b.race=function(g){return new b(function(f,k){for(var l=t(g),m=l.next();!m.done;m=l.next())d(m.value).B(f,k)})};b.all=function(g){var f=t(g),k=f.next();return k.done?d([]):new b(function(l,m){function z(ka){return function(la){B[ka]=la;F--;0==F&&l(B)}}var B=[],F=0;do B.push(void 0),F++,d(k.value).B(z(B.length-1),m),k=f.next();while(!k.done)})};return b});
function x(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
r("WeakMap",function(a){function b(k){this.g=(f+=Math.random()+1).toString();if(k){k=t(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function d(k){var l=typeof k;return"object"===l&&null!==k||"function"===l}function e(k){if(!x(k,g)){var l=new c;p(k,g,{value:l})}}function h(k){var l=Object[k];l&&(Object[k]=function(m){if(m instanceof c)return m;Object.isExtensible(m)&&e(m);return l(m)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),
m=new a([[k,2],[l,3]]);if(2!=m.get(k)||3!=m.get(l))return!1;m.delete(k);m.set(l,4);return!m.has(k)&&4==m.get(l)}catch(z){return!1}}())return a;var g="$jscomp_hidden_"+Math.random();h("freeze");h("preventExtensions");h("seal");var f=0;b.prototype.set=function(k,l){if(!d(k))throw Error("Invalid WeakMap key");e(k);if(!x(k,g))throw Error("WeakMap key fail: "+k);k[g][this.g]=l;return this};b.prototype.get=function(k){return d(k)&&x(k,g)?k[g][this.g]:void 0};b.prototype.has=function(k){return d(k)&&x(k,
g)&&x(k[g],this.g)};b.prototype.delete=function(k){return d(k)&&x(k,g)&&x(k[g],this.g)?delete k[g][this.g]:!1};return b});
r("Map",function(a){function b(){var f={};return f.u=f.next=f.head=f}function c(f,k){var l=f.g;return ca(function(){if(l){for(;l.head!=f.g;)l=l.u;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};l=null}return{done:!0,value:void 0}})}function d(f,k){var l=k&&typeof k;"object"==l||"function"==l?h.has(k)?l=h.get(k):(l=""+ ++g,h.set(k,l)):l="p_"+k;var m=f.h[l];if(m&&x(f.h,l))for(f=0;f<m.length;f++){var z=m[f];if(k!==k&&z.key!==z.key||k===z.key)return{id:l,list:m,index:f,o:z}}return{id:l,list:m,
index:-1,o:void 0}}function e(f){this.h={};this.g=b();this.size=0;if(f){f=t(f);for(var k;!(k=f.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var f=Object.seal({x:4}),k=new a(t([[f,"s"]]));if("s"!=k.get(f)||1!=k.size||k.get({x:4})||k.set({x:4},"t")!=k||2!=k.size)return!1;var l=k.entries(),m=l.next();if(m.done||m.value[0]!=f||"s"!=m.value[1])return!1;m=l.next();return m.done||4!=m.value[0].x||
"t"!=m.value[1]||!l.next().done?!1:!0}catch(z){return!1}}())return a;var h=new WeakMap;e.prototype.set=function(f,k){f=0===f?0:f;var l=d(this,f);l.list||(l.list=this.h[l.id]=[]);l.o?l.o.value=k:(l.o={next:this.g,u:this.g.u,head:this.g,key:f,value:k},l.list.push(l.o),this.g.u.next=l.o,this.g.u=l.o,this.size++);return this};e.prototype.delete=function(f){f=d(this,f);return f.o&&f.list?(f.list.splice(f.index,1),f.list.length||delete this.h[f.id],f.o.u.next=f.o.next,f.o.next.u=f.o.u,f.o.head=null,this.size--,
!0):!1};e.prototype.clear=function(){this.h={};this.g=this.g.u=b();this.size=0};e.prototype.has=function(f){return!!d(this,f).o};e.prototype.get=function(f){return(f=d(this,f).o)&&f.value};e.prototype.entries=function(){return c(this,function(f){return[f.key,f.value]})};e.prototype.keys=function(){return c(this,function(f){return f.key})};e.prototype.values=function(){return c(this,function(f){return f.value})};e.prototype.forEach=function(f,k){for(var l=this.entries(),m;!(m=l.next()).done;)m=m.value,
f.call(k,m[1],m[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var g=0;return e});
r("Set",function(a){function b(c){this.g=new Map;if(c){c=t(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.g.size}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),d=new a(t([c]));if(!d.has(c)||1!=d.size||d.add(c)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var e=d.entries(),h=e.next();if(h.done||h.value[0]!=c||h.value[1]!=c)return!1;h=e.next();return h.done||h.value[0]==c||4!=h.value[0].x||
h.value[1]!=h.value[0]?!1:e.next().done}catch(g){return!1}}())return a;b.prototype.add=function(c){c=0===c?0:c;this.g.set(c,c);this.size=this.g.size;return this};b.prototype.delete=function(c){c=this.g.delete(c);this.size=this.g.size;return c};b.prototype.clear=function(){this.g.clear();this.size=0};b.prototype.has=function(c){return this.g.has(c)};b.prototype.entries=function(){return this.g.entries()};b.prototype.values=function(){return this.g.values()};b.prototype.keys=b.prototype.values;b.prototype[Symbol.iterator]=
b.prototype.values;b.prototype.forEach=function(c,d){var e=this;this.g.forEach(function(h){return c.call(d,h,h,e)})};return b});r("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,h=0;h<e;h++){var g=d[h];if(b.call(c,g,h,d)){b=g;break a}}b=void 0}return b}});r("Number.isFinite",function(a){return a?a:function(b){return"number"!==typeof b?!1:!isNaN(b)&&Infinity!==b&&-Infinity!==b}});
function ua(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var h=c++;return{value:b(h,a[h]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}r("Array.prototype.keys",function(a){return a?a:function(){return ua(this,function(b){return b})}});r("Number.isInteger",function(a){return a?a:function(b){return Number.isFinite(b)?b===Math.floor(b):!1}});
r("Array.prototype.values",function(a){return a?a:function(){return ua(this,function(b,c){return c})}});r("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});r("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var h=d[c];if(h===b||Object.is(h,b))return!0}return!1}});
r("String.prototype.includes",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==this.indexOf(b,c||0)}});var y=this||self;function A(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}
function C(a,b){a=a.split(".");var c=y;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b}function va(a,b){function c(){}c.prototype=b.prototype;a.U=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.fa=function(d,e,h){for(var g=Array(arguments.length-2),f=2;f<arguments.length;f++)g[f-2]=arguments[f];return b.prototype[e].apply(d,g)}};function D(a,b){a=Error.call(this,a);this.message=a.message;"stack"in a&&(this.stack=a.stack);b=void 0===b?2:b;this.code=1E4<b?Math.floor(b/1E4):b}var E=Error;D.prototype=da(E.prototype);D.prototype.constructor=D;if(ja)ja(D,E);else for(var G in E)if("prototype"!=G)if(Object.defineProperties){var wa=Object.getOwnPropertyDescriptor(E,G);wa&&Object.defineProperty(D,G,wa)}else D[G]=E[G];D.U=E.prototype;C("microapps.ErrorCode.CANCELLED",1);C("microapps.ErrorCode.UNKNOWN",2);C("microapps.ErrorCode.INVALID_ARGUMENT",3);C("microapps.ErrorCode.DEADLINE_EXCEEDED",4);C("microapps.ErrorCode.NOT_FOUND",5);C("microapps.ErrorCode.ALREADY_EXISTS",6);C("microapps.ErrorCode.PERMISSION_DENIED",7);C("microapps.ErrorCode.RESOURCE_EXHAUSTED",8);C("microapps.ErrorCode.FAILED_PRECONDITION",9);C("microapps.ErrorCode.ABORTED",10);C("microapps.ErrorCode.OUT_OF_RANGE",11);C("microapps.ErrorCode.UNIMPLEMENTED",12);
C("microapps.ErrorCode.INTERNAL",13);C("microapps.ErrorCode.UNAVAILABLE",14);C("microapps.ErrorCode.DATA_LOSS",15);C("microapps.ErrorCode.UNAUTHENTICATED",16);var H=null;function xa(){}n=xa.prototype;n.C=function(){H().C()};n.K=function(a){return H().K(a)};n.R=function(a){return H().R(a)};n.S=function(a){return H().S(a)};n.F=function(a){return H().F(a)};n.J=function(a){return H().J(a)};n.M=function(a){return H().M(a)};n.O=function(a){return H().O(a)};n.N=function(a){return H().N(a)};n.P=function(a){return H().P(a)};n.v=function(a){return H().v(a)};n.I=function(a){return H().I(a)};var ya=null;function za(){}za.prototype.L=function(){return ya().L()};za.prototype.G=function(a){return ya().G(a)};var Aa=new Set(["image/jpeg","video/*","application/pdf"]),Ba=new Set(["camera","files"]);function Ca(a,b){a=String(a).toLowerCase();b=String(b).toLowerCase();return a<b?-1:a==b?0:1};var I,J;a:{for(var Da=["CLOSURE_FLAGS"],K=y,Ea=0;Ea<Da.length;Ea++)if(K=K[Da[Ea]],null==K){J=null;break a}J=K}var Fa=J&&J[610401301];I=null!=Fa?Fa:!1;function L(){var a=y.navigator;return a&&(a=a.userAgent)?a:""}var M,Ga=y.navigator;M=Ga?Ga.userAgentData||null:null;function Ha(a){return I?M?M.brands.some(function(b){return(b=b.brand)&&-1!=b.indexOf(a)}):!1:!1}function N(a){return-1!=L().indexOf(a)};function O(){return I?!!M&&0<M.brands.length:!1}function Ia(){return O()?Ha("Chromium"):(N("Chrome")||N("CriOS"))&&!(O()?0:N("Edge"))||N("Silk")};var Ja=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ka=Array.prototype.every?function(a,b){return Array.prototype.every.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&!b.call(void 0,d[e],e,a))return!1;return!0};
function P(a){return Array.prototype.concat.apply([],arguments)};function La(a){La[" "](a);return a}La[" "]=function(){};var Ma=N("Gecko")&&!(-1!=L().toLowerCase().indexOf("webkit")&&!N("Edge"))&&!(N("Trident")||N("MSIE"))&&!N("Edge"),Na=I&&M&&M.platform?"Android"===M.platform:N("Android"),Oa=N("iPhone")&&!N("iPod")&&!N("iPad")||N("iPad")||N("iPod");!N("Android")||Ia();Ia();N("Safari")&&(Ia()||(O()?0:N("Coast"))||(O()?0:N("Opera"))||(O()?0:N("Edge"))||(O()?Ha("Microsoft Edge"):N("Edg/"))||O()&&Ha("Opera"));var Pa=/^(http:\/\/localhost\.corp|https:\/\/microapps(-(autopush|preprod|prod-tt|daily-[0-6])\.sandbox)?)\.google\.com(:[0-9]+)?$/;function Qa(a){var b=0,c;for(c in a)b++;return b}function Ra(a,b){for(var c in a)if(!(c in b)||a[c]!==b[c])return!1;for(var d in b)if(!(d in a))return!1;return!0};function Q(a,b){this.g=b===Sa?a:""}Q.prototype.toString=function(){return this.g.toString()};var Sa={},R=new Q("about:blank",Sa);var Ta=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function Ua(a){return a?decodeURI(a):a};function Va(a){if(a.self===a.top)return!1;if(a.location.origin&&a.location.ancestorOrigins){var b=a.location.origin;return Ka(a.location.ancestorOrigins,function(c){var d=Ua(c.match(Ta)[3]||null)||"";return 0==Ca(".google.com",d.slice(d.length-11))||c===b})}return!1}function Wa(a){return a.location.ancestorOrigins&&a.location.ancestorOrigins.length?Pa.test(a.location.ancestorOrigins[0]):!1};var Xa=/\[gpay-microapps\/(\d+(\.\d+)*)[^\]]*\]/;function Ya(a,b,c){this.g=a;this.h=b;this.i=c}function Za(a){a=a.split(".");return new Ya(Number(a[0]||""),Number(a[1]||""),Number(a[2]||""))}
function S(){var a={j:"",l:!1,h:!1,g:0};Na?a.j="android":Oa&&(a.j="ios");var b=Xa.exec(L().toLocaleLowerCase());b&&0<b.length&&("android"==a.j&&b[0].includes("dev")?a.l=!0:"ios"==a.j&&b[0].includes("213.999.9999")?a.l=!0:b&&1<b.length&&(a.i=Za(b[1])),b[0].includes("flutter")&&(a.h=!0),b[0].includes("merchant")?a.g=5:a.g=$a(a));return a}function $a(a){if(!a)return 0;switch(a.j){case "ios":return a.h?2:4;case "android":return a.h?1:3;default:return 0}};function ab(){};function bb(a,b){this.type=a;this.target=b}bb.prototype.g=function(){};var cb=function(){if(!y.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{y.addEventListener("test",function(){},b),y.removeEventListener("test",function(){},b)}catch(c){}return a}();function T(a){bb.call(this,a?a.type:"");this.relatedTarget=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.H=null;if(a){var b=this.type=a.type,c=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;var d=a.relatedTarget;if(d){if(Ma){a:{try{La(d.nodeName);var e=!0;break a}catch(h){}e=!1}e||(d=
null)}}else"mouseover"==b?d=a.fromElement:"mouseout"==b&&(d=a.toElement);this.relatedTarget=d;c?(this.clientX=void 0!==c.clientX?c.clientX:c.pageX,this.clientY=void 0!==c.clientY?c.clientY:c.pageY,this.screenX=c.screenX||0,this.screenY=c.screenY||0):(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=
a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:db[a.pointerType]||"";this.state=a.state;this.H=a;a.defaultPrevented&&T.U.g.call(this)}}va(T,bb);var db={2:"touch",3:"pen",4:"mouse"};T.prototype.g=function(){T.U.g.call(this);var a=this.H;a.preventDefault?a.preventDefault():a.returnValue=!1};var eb="closure_listenable_"+(1E6*Math.random()|0);var fb=0;function gb(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.h=e;this.key=++fb;this.g=this.D=!1}function hb(a){a.g=!0;a.listener=null;a.proxy=null;a.src=null;a.h=null};function ib(a){this.src=a;this.g={};this.h=0}ib.prototype.add=function(a,b,c,d,e){var h=a.toString();a=this.g[h];a||(a=this.g[h]=[],this.h++);var g;a:{for(g=0;g<a.length;++g){var f=a[g];if(!f.g&&f.listener==b&&f.capture==!!d&&f.h==e)break a}g=-1}-1<g?(b=a[g],c||(b.D=!1)):(b=new gb(b,this.src,h,!!d,e),b.D=c,a.push(b));return b};var jb="closure_lm_"+(1E6*Math.random()|0),kb={},lb=0;function mb(a,b,c,d,e){if(d&&d.once)return U(a,b,c,d,e);if(Array.isArray(b)){for(var h=0;h<b.length;h++)mb(a,b[h],c,d,e);return null}c=nb(c);return a&&a[eb]?a.g(b,c,A(d)?!!d.capture:!!d,e):ob(a,b,c,!1,d,e)}
function ob(a,b,c,d,e,h){if(!b)throw Error("Invalid event type");var g=A(e)?!!e.capture:!!e,f=pb(a);f||(a[jb]=f=new ib(a));c=f.add(b,c,d,g,h);if(c.proxy)return c;d=qb();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)cb||(e=g),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(rb(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");lb++;return c}
function qb(){function a(c){return b.call(a.src,a.listener,c)}var b=sb;return a}function U(a,b,c,d,e){if(Array.isArray(b)){for(var h=0;h<b.length;h++)U(a,b[h],c,d,e);return null}c=nb(c);return a&&a[eb]?a.h(b,c,A(d)?!!d.capture:!!d,e):ob(a,b,c,!0,d,e)}function rb(a){return a in kb?kb[a]:kb[a]="on"+a}
function sb(a,b){if(a.g)a=!0;else{b=new T(b,this);var c=a.listener,d=a.h||a.src;if(a.D&&"number"!==typeof a&&a&&!a.g){var e=a.src;if(e&&e[eb])e.i(a);else{var h=a.type,g=a.proxy;e.removeEventListener?e.removeEventListener(h,g,a.capture):e.detachEvent?e.detachEvent(rb(h),g):e.addListener&&e.removeListener&&e.removeListener(g);lb--;if(h=pb(e)){g=a.type;var f;if(f=g in h.g){f=h.g[g];var k=Ja(f,a),l;(l=0<=k)&&Array.prototype.splice.call(f,k,1);f=l}f&&(hb(a),0==h.g[g].length&&(delete h.g[g],h.h--));0==
h.h&&(h.src=null,e[jb]=null)}else hb(a)}}a=c.call(d,b)}return a}function pb(a){a=a[jb];return a instanceof ib?a:null}var tb="__closure_events_fn_"+(1E9*Math.random()>>>0);function nb(a){if("function"===typeof a)return a;a[tb]||(a[tb]=function(b){return a.handleEvent(b)});return a[tb]};function ub(){var a=this;this.promise=new Promise(function(b,c){a.resolve=b;a.reject=c})};var V=null,vb=new ub;function wb(a){var b,c,d;return w(function(e){if(1==e.g)return null==V&&(V=S()),null==V||null==V.i?e.return(!0):u(e,vb.promise,2);b=e.i;if(!b.has(a))return e.return(!1);if(V.l)return e.return(!0);c=b.get(a);d=V.i;return e.return(d.g!==c.g?d.g>c.g:d.h!==c.h?d.h>c.h:d.i>=c.i)})};var xb=new Set(["type","enum","const"]);function yb(a,b,c){a=zb(a,b,[void 0===c?"root":c]);return 0<a.length?a:null}function W(a,b,c){return"Object:"+a.join(".")+" Validation:"+b+" Constraint:"+c}function Ab(a,b){var c=a.length;if(0<c){for(var d=Array(c),e=0;e<c;e++)d[e]=a[e];a=d}else a=[];a[a.length-1]+="["+b+"]";return a}
function Bb(a,b,c){var d=[];Object.keys(a).forEach(function(e){if(!xb.has(e)){var h=!1;switch(e){case "multipleOf":h="number"!==typeof b||0===b%a[e];break;case "minimum":h=b>=a[e]||a.exclusiveMinimum&&b>a[e];break;case "maximum":h=b<=a[e]||a.exclusiveMaximum&&b<a[e];break;case "exclusiveMinimum":case "exclusiveMaximum":break;default:throw Error("Unsupported numeric keywords:"+e);}h||d.push(W(c,e,a[e].toString()))}});return d}
function Cb(a,b,c){var d=[];Object.keys(a).forEach(function(e){if(!xb.has(e)){switch(e){case "pattern":var h=(new RegExp(a[e])).test(b);break;case "minLength":h=b.length>=a[e];break;case "maxLength":h=b.length<=a[e];break;default:throw Error("Unsupported string keywords:"+e);}h||d.push(W(c,e,a[e].toString()))}});return d}
function Db(a,b,c){var d=[];Object.keys(a).forEach(function(e){if(!xb.has(e)){var h=a[e];switch(e){case "items":if(Array.isArray(h))for(e=0;e<h.length;e++){var g=Ab(c,e);g=zb(h[e],b[e],g);null!==g&&(d=P(d,g))}else for(e=0;e<b.length;e++)g=Ab(c,e),g=zb(h,b[e],g),null!==g&&(d=P(d,g));break;case "maxItems":b.length>h&&d.push(W(c,e,h.toString()));break;case "minItems":b.length<h&&d.push(W(c,e,h.toString()));break;case "uniqueItems":if("boolean"!==typeof h)d.push(W(c,e,h.toString()));else if(h){g=new Set;
for(var f=0;f<b.length;f++){var k=JSON.stringify(b[f]);if(g.has(k)){d.push(W(c,e,h.toString()));break}else g.add(k)}}break;default:throw Error("Unsupported array keywords:"+e);}}});return d}
function Eb(a,b,c){var d=[];Object.keys(a).forEach(function(e){if(!xb.has(e)){var h=a[e];switch(e){case "required":for(var g=t(h),f=g.next();!f.done;f=g.next())f=f.value,void 0===b[f]&&d.push(W(c,e,f));break;case "properties":Object.keys(b).forEach(function(k){void 0!==h[k]&&(k=zb(h[k],b[k],P(c,k)),null!==k&&(d=P(d,k)))});break;case "minProperties":Qa(b)<h&&d.push(W(c,e,h.toString()));break;case "maxProperties":Qa(b)>h&&d.push(W(c,e,h.toString()));break;case "patternProperties":case "additionalProperties":case "dependencies":case "propertyNames":throw Error("Unsupported object keywords:"+
e);default:throw Error("Unknown object keywords:"+e);}}});return d}
function zb(a,b,c){var d=[];if(null!=a.type){d=a.type;switch(d){case "string":var e="string"===typeof b;break;case "number":e="number"===typeof b;break;case "boolean":e="boolean"===typeof b;break;case "null":e=null===b;break;case "object":e=A(b)&&!Array.isArray(b);break;case "integer":e="number"===typeof b&&Number.isInteger(b);break;case "array":e=Array.isArray(b);break;case "date":e=A(b)&&"function"==typeof b.getFullYear;break;default:throw Error("Unsupported field type: "+d);}d=e?[]:[W(c,"type",
d)]}if(0==d.length&&null!=a["enum"]){d=a["enum"];e=!1;if(A(b))for(var h=t(d),g=h.next();!g.done;g=h.next()){if(Ra(b,g.value)){e=!0;break}}else for(h=t(d),g=h.next();!g.done;g=h.next())if(b===g.value){e=!0;break}d=e?[]:[W(c,"enum",JSON.stringify(d))]}0==d.length&&null!=a["const"]&&(d=a["const"],d=(A(b)?Ra(d,b):b===d)?[]:[W(c,"const",JSON.stringify(d))]);if(d.length)return d;"number"===typeof b?d=Bb(a,b,c):"string"===typeof b?d=Cb(a,b,c):Array.isArray(b)?d=Db(a,b,c):A(b)&&!Array.isArray(b)&&(d=Eb(a,
b,c));return d};var Fb={type:"object",properties:{apiVersion:{type:"number"},apiVersionMinor:{type:"number"},allowedPaymentMethods:{type:"array",items:{type:"object",required:["type"]},minItems:1},transactionInfo:{type:"object",properties:{totalPrice:{type:"string",pattern:"^[0-9]+(\\.[0-9][0-9])?$"},totalPriceStatus:{type:"string"},currencyCode:{type:"string"},transactionNote:{type:"string"}},required:["totalPriceStatus","currencyCode"]}},required:["apiVersion","apiVersionMinor","allowedPaymentMethods","transactionInfo"]},
Gb={type:"object",properties:{type:{type:"string"},parameters:{type:"object",required:["payeeVpa","payeeName","mcc","transactionReferenceId"],properties:{payeeName:{type:"string",minLength:1},transactionReferenceId:{type:"string",minLength:1}}},tokenizationSpecification:{type:"object",properties:{type:{type:"string","enum":["DIRECT"]}},required:["type"]}},required:["parameters","tokenizationSpecification","type"]},Hb={type:"object",properties:{text:{type:"string",maxLength:150},url:{type:"string",
maxLength:2E3,pattern:"^https://microapps.google.com/"},title:{type:"string",maxLength:80},imageUrl:{type:"string",maxLength:2E3},microappId:{type:"string",maxLength:25}}},Ib={type:"object",properties:{allowedMimeTypes:{type:"array",items:{type:"string"},minItems:1},allowedSources:{type:"array",items:{type:"string"}},cameraDirection:{type:"string","enum":["front","back"]},maxVideoSeconds:{type:"number",minimum:1,maximum:5}},required:["allowedMimeTypes"]};function Jb(a){var b=yb(Fb,a,"paymentRequest");if(b)return X(JSON.stringify(b));b=t(a.allowedPaymentMethods);for(var c=b.next();!c.done;c=b.next()){c=c.value;var d;a:{if("UPI"===c.type&&(d=yb(Gb,c))){d=JSON.stringify(d);break a}d=null}if(d)return X(d);if(c=Kb(c,a.transactionInfo))return X(c)}return a.environment&&(a=Lb(a.allowedPaymentMethods,a.environment))?X(a):null}function Mb(a){return null!=a&&A(a)?null:X("Valid order object is required for this API.")}
function Nb(a){if(null==a||!A(a))return X("Valid mediaRequest object is required for this API.");var b=yb(Ib,a,"mediaRequest");if(b)return X(JSON.stringify(b));b=t(a.allowedMimeTypes);for(var c=b.next();!c.done;c=b.next())if(c=Aa.has(c.value)?null:"Request must contain supported media types.")return X(c);if(b=1==a.allowedMimeTypes.length&&"video/*"===a.allowedMimeTypes[0])b=S(),b=!(b.l||(1==b.g||3==b.g)&&54<b.i.g||Ob(b)||2===b.g&&115<b.i.g);if(b)return X("Client does not support video requests. Please update the Google Pay app.");
b=S();b=b.l||(1==b.g||3==b.g)&&57<b.i.g||Ob(b)||2===b.g&&115<b.i.g;if(1===a.allowedMimeTypes.length&&"application/pdf"===a.allowedMimeTypes[0]&&!b)return X("Client does not support file requests. Please update the Google Pay app.");if(!a.allowedSources)return null;c=t(a.allowedSources);for(var d=c.next();!d.done;d=c.next())if(d=Ba.has(d.value)?null:"Request must contain supported media sources.")return X(d);return 1!==a.allowedSources.length||"files"!==a.allowedSources[0]||b?1===a.allowedSources.length&&
"camera"===a.allowedSources[0]&&a.allowedMimeTypes.includes("application/pdf")?X('Not possible to request "application/pdf" MIME type with only "camera" in "allowedSources"'):null:X("CLIENT_UNSUPPORTED_FOR_FILES")}
function Kb(a,b){if("NOT_CURRENTLY_KNOWN"!==b.totalPriceStatus&&!(0<Number(b.totalPrice)))return"Amount must be greater than 0";if("UPI"===a.type){if("FINAL"!==b.totalPriceStatus)return'Only "FINAL" is supported now in totalPriceStatus for UPI payment type.';if("INR"!==b.currencyCode)return'Only "INR" is currently supported in currencyCode for UPI payment type.'}else if("CARD"===a.type&&!b.transactionId)return"transactionInfo.transactionId is required.";return null}
function Lb(a,b){return a.find(function(c){return"CARD"===c.type})?"TEST"!=b?'only "TEST" environment is supported for CARD payment type.':null:'"environment" is supported for CARD payment type only.'}function Ob(a){var b=a.i;return 5==a.g&&(1<b.g||1==b.g&&23<=b.h)}function X(a){return new D(a,3)};function Pb(a){var b=this;this.g=a;this.j=0;this.h=new Map;this.l=new Promise(function(c){return b.s=c});this.g.addEventListener("message",this.i.bind(this));this.g.start()}Pb.prototype.i=function(a){if((a=a.data)&&null!=a.id)if(0===a.type)"acceptConnection"===a.name&&this.s();else if(1===a.type){var b=a.id,c=this.h.get(b);c&&(this.h.delete(b),null!=a.error?c.reject(new D("Request "+a.name+" failed: "+a.error,a.errorCode)):c.resolve(a.data))}};
Pb.prototype.m=function(a,b,c){var d=this;c=void 0===c?!0:c;var e=++this.j,h=Promise.resolve();c&&(h=new Promise(function(f,k){d.h.set(e,{resolve:f,reject:k})}));var g={id:e,type:0,name:a,data:b,isResponseRequired:c};this.l.then(function(){d.g.postMessage(g)});return h};function Qb(a){this.g=a;this.h={}}va(Qb,ab);var Rb=[];function Sb(a,b,c){var d="nativeBridge";Array.isArray(d)||(d&&(Rb[0]=d.toString()),d=Rb);for(var e=0;e<d.length;e++){var h=mb(b,d[e],c||a.handleEvent,!1,a.g||a);if(!h)break;a.h[h.key]=h}}Qb.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function Tb(a){this.h=a;this.i=new Qb(this);Ub(this);this.g=null}function Vb(a,b){Na?(a=a.h.paisaJSHost_,null!=a&&a.callNative(JSON.stringify(b))):Oa&&(a=a.h.webkit.messageHandlers.paisaJSHost_,null!=a&&a.postMessage(JSON.stringify(b)))}function Wb(a,b){a.g=b}function Ub(a){Sb(a.i,a.h,function(b){b=b.H;null!=b.detail&&null!=a.g&&a.g(b.detail)})};function Xb(a){var b=this;this.l=Math.floor(65535*Math.random());this.j=this.h=null;this.g=new Map;this.i=new Tb(a);Wb(this.i,function(c){if(!(!c||"object"!==typeof c&&"function"!==typeof c||"string"!==typeof c.status||"success"!==c.status&&"failure"!==c.status||"number"!==typeof c.id)){var d=c.data;if(c.id===b.j)null!=b.h&&"string"===typeof d&&b.h.resolve(d);else{var e=b.g.get(c.id);e&&(b.g.delete(c.id),c.method!==e.request.method?e.T.reject(new D("Method names in request and response are not the same. Request:"+
(e.request.method+" Response:"+c.method))):"success"===c.status?e.T.resolve(d):e.T.reject(new D(d,c.errorCode)))}}});this.h=new ub;this.j=Yb(this);Vb(this.i,{token:"",method:"startConnection",id:this.j,data:{},isResponseRequired:!0});this.s=this.h.promise}
Xb.prototype.m=function(a,b,c){c=void 0===c?!0:c;var d=this,e,h,g,f;return w(function(k){if(1==k.g)return u(k,d.s,2);e=k.i;h=Yb(d);g={token:e,method:a,id:h,data:b,isResponseRequired:c};Vb(d.i,g);if(!c)return k.return(Promise.resolve());f=new ub;d.g.set(h,{T:f,request:g});return k.return(f.promise)})};function Yb(a){var b=a.l;a.l=(b+1)%65535;a.g.has(b);return b};var Zb=null;
function $b(){var a=window;if(a.self===a.top&&S().h)this.g=new Xb(a);else{var b=Zb=new MessageChannel;try{var c=a.self!==a.top}catch(e){c=!0}if(!c)throw Error("Unsupported environment: expected running in iframe");c=new Pb(b.port1);if(!a.location.ancestorOrigins||!a.location.ancestorOrigins.length)throw Error("unsupported environment");var d=a.location.ancestorOrigins[0];if(!Pa.test(d))throw Error("unknown viewer origin");a.parent.postMessage({type:0,name:"requestConnection"},d,[b.port2]);this.g=
c}}$b.prototype.m=function(a,b,c){return this.g.m(a,b,void 0===c?!0:c)};/*

 SPDX-License-Identifier: Apache-2.0
*/
var ac;try{new URL("s://g"),ac=!0}catch(a){ac=!1}var bc=ac;function cc(){if(!bc){a:{var a=document.createElement("a");try{a.href=R}catch(b){a=void 0;break a}a=a.protocol;a=":"===a||""===a?"https:":a}return a}try{a=new URL(R)}catch(b){return"https:"}return a.protocol};var dc=null;function ec(){var a=window;this.g=new $b;this.h=a}function Y(){dc||(dc=new ec);return dc}n=ec.prototype;n.C=function(){var a;(a=this.h.self===this.h.top)||(a=this.h,a=Va(a)&&Wa(a));if(a)fc(this,"sdkload");else{a=this.h.location;var b=R instanceof Q?R instanceof Q&&R.constructor===Q?R.g:"type_error:SafeUrl":"javascript:"!==cc()?R:void 0;void 0!==b&&(a.href=b)}};function fc(a,b,c){a.g.m("appLoadingComplete",{loadType:b,loadTimeMs:void 0===c?null:c})}
n.K=function(a){var b=this,c,d,e,h,g;return w(function(f){if(1==f.g)return c=a||{},d="getIdentity",e=c.testVersion,u(f,b.v("nativeGetIdentity"),2);if(3!=f.g)return h=f.i,u(f,b.v("webGetIdentity"),3);g=f.i;e&&"v1"===e.toLowerCase()?d="getIdentity":e&&"v2"===e.toLowerCase()?d="nativeGetIdentity":g?d="getIdentity":h&&(d="nativeGetIdentity");return f.return(b.g.m(d,c))})};n.L=function(){return this.g.m("getPeerInfo",{})};
n.R=function(a){var b=Jb(a);return b?Promise.reject(b):this.g.m("requestPayment",a)};n.S=function(a){var b;if(b=(b=yb(Hb,a,"sharingRequest"))?X(JSON.stringify(b)):null)return Promise.reject(b);gc(a.imageUrl)||(a.imageUrl="");return this.g.m("requestSharing",a)};n.F=function(a){var b=this,c,d;return w(function(e){if(1==e.g)return(c=Mb(a))?e.return(Promise.reject(c)):u(e,b.g.m("createOrder",a),2);d=e.i;"object"===typeof d&&(d.toString=function(){return JSON.stringify(d)});return e.return(d)})};
n.G=function(a){var b=this,c;return w(function(d){return(c=Mb(a))?d.return(Promise.reject(c)):d.return(b.g.m("createPeerOrder",a))})};n.J=function(a){return this.g.m("getCurrentLocation",a||{})};n.M=function(a){return this.g.m("getPhoneNumber",a||{})};n.O=function(a){this.g.m("openUrl",a).catch(function(){})};n.N=function(a){return this.g.m("openGpayPage",a||{})};n.P=function(a){var b=Nb(a);return b?Promise.reject(b):this.g.m("requestMedia",a)};n.I=function(a){return this.g.m("getAddress",a||{})};
n.v=function(a){return wb(a)};function gc(a){if(!a||"https"!==(a.match(Ta)[1]||"").toLowerCase())return!1;var b=Ua(a.match(Ta)[3]||null)||"";return[".google.com",".googleapis.com",".gstatic.com",".googleusercontent.com"].some(function(c){return 0==Ca(c,b.slice(b.length-c.length))})}
(function(a){var b,c;return w(function(d){b=window;if(!(Va(b)&&Wa(b)||b.self===b.top&&S().h))return d.return();c=new Map;a().then(function(e){e=e.allowedFeatureConfigs;Array.isArray(e)&&(e.forEach(function(h){return c.set(h.feature,Za(h.minVersion||""))}),vb.resolve(c))});d.g=0})})(function(){return Y().g.m("getAllowedFeatureConfigs",{})});
(function(a){var b=window;if(b.self===b.top&&S().h)if(b.PerformanceObserver&&(b.PerformanceObserver.supportedEntryTypes||[]).includes("navigation"))try{(new b.PerformanceObserver(function(c){c=t(c.getEntries());for(var d=c.next();!d.done;d=c.next())d=d.value,"navigate"===d.type&&0<d.duration&&a(d.duration)})).observe({type:"navigation",buffered:!0})}catch(c){U(b,"load",function(){return a(null)})}else U(b,"load",function(){return a(null)})})(function(a){return fc(Y(),"onload",a)});
(function(a){try{var b=window;(Va(b)&&Wa(b)||b.self===b.top&&S().h)&&U(b,"load",function(){if(b.performance&&b.performance.getEntriesByType&&0!=b.performance.getEntriesByType("paint").length){var c=b.performance.getEntriesByType("paint");c=t(c);for(var d=c.next();!d.done;d=c.next())switch(d=d.value,d.name){case "first-contentful-paint":a(d.startTime+d.duration)}}})}catch(c){}})(function(a){return void fc(Y(),"fcp",a)});var Z;H=function(){return Y()};Z=new xa;var hc;ya=function(){return Y()};hc=new za;C("microapps.getIdentity",Z.K);C("microapps.requestPayment",Z.R);C("microapps.createOrder",Z.F);C("microapps.createPeerOrder",hc.G);C("microapps.initialize",Z.C);C("microapps.getCurrentLocation",Z.J);C("microapps.getPhoneNumber",Z.M);C("microapps.getPeerInfo",hc.L);C("microapps.openUrl",Z.O);C("microapps.openGpayPage",Z.N);C("microapps.requestSharing",Z.S);C("microapps.requestMedia",Z.P);C("microapps.getAddress",Z.I);
C("microapps.checkFeatureAvailability",Z.v);C("microapps.environment",function(){return Xa.test(L().toLocaleLowerCase())?"gpay-microapps":""});}).call(this);
